### ISSUE TITLE
Minimal Code example html fails with "AudioContext suspended"

### ISSUE THREAD

**Issue by vishnumadhu365** [met4citizen/TalkingHead#8] opened 2024-03-01 12:36 UTC
Facing the below error while trying the Minimal Code sample html.

<img width="604" alt="image" src="https://github.com/met4citizen/TalkingHead/assets/33803027/2fcab90b-c15e-4438-baf7-c2b89e1575eb">
<br>https://goo.gl/7K7WLu --> suggests we might have to create some click activity before initializing AudioContext.

Amazing work with TalkingHead !!!

**Comment by met4citizen** [comment] 2024-03-01 17:19
The first message is merely a notice or warning that can't be avoided. The warning appears because the TalkingHead class initializes the AudioContext before the document has received any user gesture. This type of initialization is permitted, but some browsers still give this notice to inform us about their policy, which restricts the app from playing audio before the first user interaction. The class follows the instruction and internally tries to call resume before initiating any audio playback.

The "Can't play audio" message, however, suggests that there is indeed a call to the `speakText` or `speakAudio` method before the user has interacted with the app, thus breaking the browser policy. I couldn't reproduce that error with the Minimal code, and in the original code the only call to `speakText` is inside the click event handler, which is a user action.

Did you make any changes to the example code? - If you did, you have to make sure that the user has interacted with the app in some way before calling `speakText` or `speakAudio`.

**Comment by met4citizen** [comment] 2024-03-02 07:03
I just changed the log message when the AudioContext resume fails, so that the reason for the error is a bit clearer. The change will be in the upcoming release. Thank you for bringing this to my attention. I will close this issue, but feel free to ask further questions, if any.

**Closed by met4citizen** 2024-03-02 07:03 UTC
